User controller #7
FundacioEsplaiJava2024/ToDoApi-grupo-4 pull request #13
Opened 2024-07-19 09:50 UTC by AleXKiD31

Fixed some errors from ColumnController2 and added UserController, UserServices, UserRepository and User (Entity).
Now when you send a request from postman for users or columns like this:
[GET] http://127.0.0.1:8080/api/columns/{id}
[GET] http://127.0.0.1:8080/api/user

It will show you the column information and/or user information from our database.
You can also create, update or delete.

columns
[PUT] http://127.0.0.1:8080/api/columns/edit/{id}
[DELETE] http://127.0.0.1:8080/api/columns/del/{id}

users
[GET] http://127.0.0.1:8080/api/user/{id}
[PUT] http://127.0.0.1:8080/api/user/{id}
[DELETE] http://127.0.0.1:8080/api/user/{id}

2024-07-22 07:22 UTC, AlexFlFe approved these changes

2024-07-22 07:57 UTC, JordiJT99 approved these changes

2024-07-22 10:45 UTC, Albamph approved these changes

2024-07-23 07:35 UTC, SaraVictorFernandez requested changes
Classes should be named using camel case

2024-07-23 07:35 UTC, SaraVictorFernandez commented on api/src/main/java/com/grupo4/todolist/api/Domain/Entities/column_todo.java
> +public class column_todo {
Las clases en Java se escriben en CamelCase (con la primera letra mayúscula para distinguirlos de las variables)

https://es.wikipedia.org/wiki/Camel_case

2024-07-23 07:40 UTC, AleXKiD31 commented on api/src/main/java/com/grupo4/todolist/api/Domain/Entities/column_todo.java
> +public class column_todo {
Done!

2024-07-23 07:50 UTC, SaraVictorFernandez approved these changes

2024-07-23 07:50 UTC, merged