Project controller #8
FundacioEsplaiJava2024/ToDoApi-grupo-4 pull request #15
Opened 2024-07-23 09:16 UTC by AleXKiD31

Added ProjectController.

[GET] http://127.0.0.1:8080/api/columns/{id}
[PUT] http://127.0.0.1:8080/api/columns/edit/{id}
[DEL] http://127.0.0.1:8080/api/columns/del/{id}

#8

2024-07-23 10:19 UTC, kianMIC approved these changes

2024-07-23 10:21 UTC, AlexFlFe approved these changes

2024-07-23 10:28 UTC, Albamph approved these changes

2024-07-24 08:17 UTC, SaraVictorFernandez requested changes

2024-07-24 08:17 UTC, SaraVictorFernandez commented on api/src/main/java/com/grupo4/todolist/api/Controllers/ProjectController.java
> +    private ProjectService ProjectService;
Variables should be named in camel case, with the first letter in lowercase (projectService)

2024-07-24 08:19 UTC, AleXKiD31 commented on api/src/main/java/com/grupo4/todolist/api/Controllers/ProjectController.java
> +    private ProjectService ProjectService;
Done!

2024-07-24 08:19 UTC, SaraVictorFernandez approved these changes

2024-07-24 08:19 UTC, merged